### ISSUE TITLE
Firefox Extension Not Working

### ISSUE THREAD

**Issue by MadDog443** [NeonGamerBot-QK/crunchyroll-comments#1]
I get the corrupted extension when trying to load the ZIP file and when attempting to use the one on the Firefox store it does nothing.

**Comment by NeonGamerBot-QK** [comment]
Seems to be an issue with your Firefox try [this](https://support.mozilla.org/en-US/kb/unable-install-add-ons-extensions-or-themes) or update ur Firefox

**Comment by NeonGamerBot-QK** [comment]
> Seems to be an issue with your Firefox try [this](https://support.mozilla.org/en-US/kb/unable-install-add-ons-extensions-or-themes) or update ur Firefox

Corrupt extension files

Corrupt extension configuration files can cause problems when trying to install an extension. Deleting these files will make Firefox recreate them (removing any corruption) the next time it starts. You won't lose your extensions or their settings by deleting these files.
Open your profile folder:
        Click the menu button Fx89menuButton, click Help and select More Troubleshooting Information. The Troubleshooting Information tab will open.
        Under the Application Basics section next to Profile Directory, click Open Directory. Your profile folder will open. 
    Note: If you are unable to open or use Firefox, follow the instructions in [Finding your profile without opening Firefox](https://support.mozilla.org/en-US/kb/profiles-where-firefox-stores-user-data#w_finding-your-profile-without-opening-firefox).

 Click the Firefox menu Fx89menuButton and select Quit.
  Delete the following files:
   extensions.sqlite
   extensions.sqlite-journal (if found)
   extensions.ini
   extensions.json 
Restart Firefox.

**Comment by MadDog443** [comment]
Tried this earlier, I can find only 1 of these files, the rest are not present afaik. I'll do some more digging tomorrow...

**Comment by NeonGamerBot-QK** [comment]
Just delete the one file and if possible delete the whole profile as that should def bring back extensions
@MadDog443
